services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres_database
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: kfh_base
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    container_name: django_web
    restart: always
    command: sh -c "sleep 12 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./media:/code/media
      - ./static:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: