# Generated by Django 5.2.10 on 2026-01-27 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('unit', models.CharField(choices=[('kg', 'кг'), ('t', 'т'), ('l', 'л'), ('pcs', 'шт'), ('dozen', 'дес'), ('l_day', 'л/сут'), ('pack', 'упак')], default='kg', max_length=30)),
                ('is_animal', models.BooleanField(default=False, verbose_name='Продукция животноводства')),
                ('description', models.TextField(blank=True, verbose_name='Описание / сорт / особенности')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='main.productcategory', verbose_name='Категория')),
            ],
        ),
    ]
