# Generated by Django 5.2.10 on 2026-02-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_animal',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_photos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('t', 'т'), ('l', 'л'), ('pcs', 'шт'), ('dozen', 'дес'), ('pack', 'упак')], default='kg', max_length=30),
        ),
    ]
